name = "Hyde"
license = "MIT"
title = "I Love Learning :)))"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "Bahar's first theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.53

[author]
    name = "spf13"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"

# Site params
[params]
    copyright = "Hugooo"
    description = "here"